assetic:
    bundles:        [ 'BookBundle' ]

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Bajke\BookBundle\Entity\User
    registration:
        form:
            type: user_registration

fos_oauth_server:
    db_driver: orm
    client_class:        Bajke\BookBundle\Entity\Client
    access_token_class:  Bajke\BookBundle\Entity\AccessToken
    refresh_token_class: Bajke\BookBundle\Entity\RefreshToken
    auth_code_class:     Bajke\BookBundle\Entity\AuthCode
    authorize:
        form:
            type: fos_oauth_server_authorize
            handler: fos_oauth_server.authorize.form.handler.default
            name: fos_oauth_server_authorize_form
    service:
        storage: fos_oauth_server.storage.default
        client_manager: fos_oauth_server.client_manager.default
        access_token_manager: fos_oauth_server.access_token_manager.default
        refresh_token_manager: fos_oauth_server.refresh_token_manager.default
        auth_code_manager: fos_oauth_server.auth_code_manager.default
#        user_provider: fos_user.user_manager
        user_provider: user.oauth_user_provider
        options:
            supported_scopes: user

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    disable_csrf_role: ROLE_USER
    view:
        view_response_listener: 'force'
        formats:
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json

hwi_oauth:
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            google: googleId
#    http_client:
#        verify_peer: false
    resource_owners:
        google:
            type:                google
            client_id:           87050065138-aepg747msgoli56gd249n8vh4eu9d874.apps.googleusercontent.com
            client_secret:       LeoLlyGd42foWpT3n68D8de5
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"